### PR TITLE
Release/1.1.0

### PR DESCRIPTION
**Pull request by anxolin**
Includes:
* Add telegram tutorial (#28)
* Base dir (#29): Do not hardcode the base dir
* Fix formatting for arbitrage-free equation (#27)
* Adding infura token information (#30) (#31)

Please note that #30 is the only one not merged already in master.

I've changed the default branch to "develop" since this project follows gitflow, instead of github flow, and the version of develop can be verified in https://dfusion-docs.dev.gnosisdev.com/protocol

### CODE REVIEW

**Comment by anxolin** [comment]
Interesting! it doesn't show changes even though there's 2 commits.

So the changes were already merged to master somehow I assume. In any case, this PR should be merged to master, so we can tag a version in master

**Comment by nlordell** [comment]
@anxolin Can you maybe post a link to the diff? Maybe we should setup master branch protection rules?

*edit*: Is it this: https://github.com/gnosis/dex-docs/commit/de4e8dbcbfd19bbdb4be4e5ad5de775bbb1ffbdc

**Comment by josojo** [comment]
@anxolin you approved the merge in master over here: https://github.com/gnosis/dex-docs/pull/31

Sorry, I was not aware that we are following the gitflow. Kei merged our PRs directly into master as well the last time...

**Review by josojo — APPROVED** [review]
Approving no changes :)

**Pull request merged**
